version: '3'
services:
  db:
    image:  postgres:13
    ports:
      - '5000:5000'
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER:  postgres
      POSTGRES_PASSWORD:  pwd864
      POSTGRES_DB: document_entity
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_HOST_AUTH_METHOD: trust
    restart: always
  app:
    build: .
    depends_on:
     - db
    ports:
      - '8000:8000'
    environment:
      POSTGRES_HOST: db
    restart: always
    links:
      - db
